# Site
name: "Papi Berlin"
title: "Papi Berlin"
description: "Eine Community f체r aktive V채ter in Berlin."
meta_description: "Eine Community f체r aktive V채ter in Berlin."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: ''
email: 'mail@papiberlin.de'

permalink: /pages/:title

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-datapage-generator
  - jekyll-polyglot
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge

page_gen:
  - index_files: false
    data: resource_categories
    name: id
    dir: resourcen
    template: 'resource'

languages: ["en", "de"]
default_lang: "de"
exclude_from_localization: ["assets", "public"]
parallel_localization: true